### ISSUE TITLE
label?

### ISSUE THREAD

**Issue by srl295** [cloudfoundry-community/node-cfenv#3]
should the VCAP `label` field be used as a selector? That tends to be fixed by the service provider.

**Comment by pmuellr** [comment]
Nope.  As you say, the label is assigned by the service provider.  So, what if you need to use two instances of a service - two databases, whatever.  Would you just return the first?  This becomes a particular problem with user-provided services, which all use the label `'user-provided'` (or some such).  

Also keep in mind that service labels have been known to change as services upgrade.

The service `names`, on the other hand, are assigned by the service creator; eg, you.  You have complete control over the name.  That's why the current `getService...()` methods search by name.

**Comment by srl295** [comment]
So I hit this in the bug above — my own error, as getService* is documented as such.

However, in this case, I *am* the service creator, and I'm trying to make an SDK that will find the service instance properly.

> Also keep in mind that service labels have been known to change as services upgrade.

Yes, but as the service creator, we have chosen a regex-matchable pattern that we will stick to for the service name.

So consider this a request for a new function, `getServiceCredsByLabel()` that will match a label.

**Comment by pmuellr** [comment]
Sounds reasonable.  Feel free to create a PR with the new function, doc,
test cases, etc.

On Wed, Dec 23, 2015 at 3:19 PM, Steven R. Loomis <notifications@github.com>
wrote:

> So I hit this in the bug above — my own error, as getService* is
> documented as such.
>
> However, in this case, I *am* the service creator, and I'm trying to make
> an SDK that will find the service instance properly.
>
> Also keep in mind that service labels have been known to change as
> services upgrade.
>
> Yes, but as the service creator, we have chosen a regex-matchable pattern
> that we will stick to for the service name.
>
> So consider this a request for a new function, getServiceCredsByLabel()
> that will match a label.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry-community/node-cfenv/issues/3#issuecomment-166983703>
> .
>



-- 
Patrick Mueller
http://muellerware.org

**Comment by srl295** [comment]
will do

**Comment by jthomas** [comment]
+1 on _getServiceCredsByLabel()_. 
I was just looking to see if this had been raised.

**Comment by srl295** [comment]
@jthomas sorry - forgot to update this.
* code: here https://github.com/IBM-Bluemix/gp-js-client/blob/2641e829cc384f5f8ff9d3788b0e0bd7cd8c0285/lib/cfenv-credsbylabel.js
* test: https://github.com/IBM-Bluemix/gp-js-client/commit/2641e829cc384f5f8ff9d3788b0e0bd7cd8c0285

Next to work on PR…
