### ISSUE TITLE
add a localUrl for callbacks?

### ISSUE THREAD

**Issue by srl295** [cloudfoundry-community/node-cfenv#5]
If an app wants to call itself, could there be a `localUrl` property that is something like:

     http://localhost:<port>/

Perhaps instead of `localhost` it should be `<bind>`, unless `<bind>` is 0.0.0.0 in which case `localhost` is still appropriate?

**Comment by pmuellr** [comment]
The intention is that `appEnv.url` should be good enough for this.  The problem with this is - when running in CF - is that it will route HTTP requests back through the gorouter (and any other front-end provided by the CF installation), causing actual network traffic instead of a loopback through localhost, which wouldn't cause any network traffic.

So, you can imagine that this might be desired.

However, in such cases, if you really DID want to route right back to the same server instance you were invoked with, then it seems like you could easily avoid HTTP altogether.

So, wondering what the real use case is.

Also, a little worried that resolving `localhost:$PORT` would not always work - I would certainly **HOPE** that it would, but I'm not sure anyone does this, so seems like an edge case that could go bad at some point.

**Comment by srl295** [comment]
There's no requirement that `localhost` or `127.0.0.1`

**Comment by pmuellr** [comment]
I'm confused on what the real need is here.  What are the use cases, and expected results?

**Comment by pmuellr** [comment]
closing because of lack of interest; feel free to re-open
